default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>

development:
  <<: *default
  database: realworld-api
  host: localhost

test:
  <<: *default
  database: realworld-api-test

production:
  <<: *default
  database: realworld-api-production
  host: <%= Rails.application.credentials.database[:host] %>
